In [1]:
import numpy as np

In [4]:
arr_1d = np.array([1,2,3,4,5])
print(arr_1d[0])

1


In [5]:
print(arr_1d[2])

3


In [6]:
print(arr_1d[-1])

5


In [12]:
arr_2d = np.array([
    [1,2,3],
    [4,5,7],
    [6,8,9],
    [11,17,19]
])

print(arr_2d[0][0])
print(arr_2d[0,0])

1
1


In [13]:
print(arr_2d[-4,-3])

1


In [18]:
# 슬라이싱

arr_1d = np.array([1,2,3,4,5])

print(arr_1d[0:2])
print(arr_1d[1:2])
print(arr_1d[:4])
print(arr_1d[1:])

[1 2]
[2]
[1 2 3 4]
[2 3 4 5]


In [24]:
arr_2d = np.array([
    [1,2,3,5],
    [1,3,5,7],
    [2,4,6,9],
    [7,11,13,17]
])

print(arr_2d[0:4])

# 아래의 것은 1차원에서와 달리 결과 값이 다름
print(arr_2d[0:4][0])   
print(arr_2d[0:4,0])

[[ 1  2  3  5]
 [ 1  3  5  7]
 [ 2  4  6  9]
 [ 7 11 13 17]]
[1 2 3 5]
[1 1 2 7]


In [26]:
print(arr_2d[:,0])
print(arr_2d[:3,0])

[1 1 2 7]
[1 1 2]


In [27]:
print(arr_2d[:3,:3])

[[1 2 3]
 [1 3 5]
 [2 4 6]]


In [28]:
print(arr_2d[:3,:3])

[[1 2 3]
 [1 3 5]
 [2 4 6]]


In [31]:
#슬라이싱에서는 위의 print(arr_2d[-4,-3])와 달리 -1까지 했으나 -2까지 결과로 나옴
print(arr_2d[:-1,:-1])

[[1 2 3]
 [1 3 5]
 [2 4 6]]


In [33]:
print(arr_2d[1:3,1:3])  #2,3행 중에 2,3열

[[3 5]
 [4 6]]


In [34]:
print(arr_2d[-3:-1,-3:-1])

[[3 5]
 [4 6]]


In [35]:
type(arr_2d)

numpy.ndarray

In [36]:
print(arr_2d[1:3,0:4])
print(arr_2d[1:3,:])
print(arr_2d[1:-1,:])

[[1 3 5 7]
 [2 4 6 9]]
[[1 3 5 7]
 [2 4 6 9]]
[[1 3 5 7]
 [2 4 6 9]]


In [38]:
print(arr_2d[3,:4])
print(arr_2d[3,:])
print(arr_2d[-1,:])

[ 7 11 13 17]
[ 7 11 13 17]
[ 7 11 13 17]


In [41]:
print(arr_2d[2:,2:])
print(arr_2d[-2:,-2:])
print(arr_2d[2:4,2:4])

[[ 6  9]
 [13 17]]
[[ 6  9]
 [13 17]]
[[ 6  9]
 [13 17]]


In [42]:
# ndarray 원소별 연산

arr = np.array([0,1,-4,-16,25])
print(arr)

[  0   1  -4 -16  25]


In [46]:
arr_abs=np.abs(arr)

print(arr_abs)

[ 0  1  4 16 25]


In [44]:
arr_fabs = np.fabs(arr)

print(arr_fabs)

[ 0.  1.  4. 16. 25.]


In [47]:
arr_sqrt = np.sqrt(arr)

print(arr)
print(arr_sqrt)

[  0   1  -4 -16  25]
[ 0.  1. nan nan  5.]


C:\Users\as4761285 001\AppData\Local\Temp\ipykernel_10876\2730284698.py:1: RuntimeWarning: invalid value encountered in sqrt
  arr_sqrt = np.sqrt(arr)


In [48]:
arr_square = np.square(arr)
print(arr)
print(arr_square) 

[  0   1  -4 -16  25]
[  0   1  16 256 625]


In [49]:
arr_exp = np.exp(arr)

print(arr)
print(arr_exp)

[  0   1  -4 -16  25]
[1.00000000e+00 2.71828183e+00 1.83156389e-02 1.12535175e-07
 7.20048993e+10]


In [50]:
arr_log = np.log(arr)

print(arr)
print(arr_log)

[  0   1  -4 -16  25]
[      -inf 0.                nan        nan 3.21887582]


C:\Users\as4761285 001\AppData\Local\Temp\ipykernel_10876\1172411286.py:1: RuntimeWarning: divide by zero encountered in log
  arr_log = np.log(arr)
C:\Users\as4761285 001\AppData\Local\Temp\ipykernel_10876\1172411286.py:1: RuntimeWarning: invalid value encountered in log
  arr_log = np.log(arr)


In [51]:
arr_log10 = np.log10(arr)

print(arr)
print(arr_log10)

[  0   1  -4 -16  25]
[      -inf 0.                nan        nan 1.39794001]


C:\Users\as4761285 001\AppData\Local\Temp\ipykernel_10876\2962806155.py:1: RuntimeWarning: divide by zero encountered in log10
  arr_log10 = np.log10(arr)
C:\Users\as4761285 001\AppData\Local\Temp\ipykernel_10876\2962806155.py:1: RuntimeWarning: invalid value encountered in log10
  arr_log10 = np.log10(arr)


In [52]:
arr_sign = np.sign(arr)
print(arr)
print(arr_sign)

[  0   1  -4 -16  25]
[ 0  1 -1 -1  1]


In [53]:
arr = np.array([1.15, -2.33,3.457,-4.095])
print(arr)


[ 1.15  -2.33   3.457 -4.095]


In [57]:
arr_round = np.around(arr)
print(arr)
print(arr_round)

[ 1.15  -2.33   3.457 -4.095]
[ 1. -2.  3. -4.]


In [58]:
arr_round_1 = np.around(arr,1)
print(arr)
print(arr_round_1)

[ 1.15  -2.33   3.457 -4.095]
[ 1.2 -2.3  3.5 -4.1]


In [59]:
arr_ceil = np.ceil(arr)

print(arr)
print(arr_ceil)


[ 1.15  -2.33   3.457 -4.095]
[ 2. -2.  4. -4.]


In [61]:
arr_floor = np.floor(arr)

print(arr)
print(arr_floor)

[ 1.15  -2.33   3.457 -4.095]
[ 1. -3.  3. -5.]


In [63]:
arr_trunc = np.trunc(arr)


print(arr)
print(arr_trunc)

[ 1.15  -2.33   3.457 -4.095]
[ 1. -2.  3. -4.]


In [65]:
arr_1 = np.arange(5)
print(arr_1)

[0 1 2 3 4]


In [66]:
arr_2 = np.arange(1,10,step = 2)
print(arr_2)

[1 3 5 7 9]


In [68]:
arr_add_1 = np.add(arr_1,arr_2)

print(arr_1)
print(arr_2)
print(arr_add_1)

[0 1 2 3 4]
[1 3 5 7 9]
[ 1  4  7 10 13]


In [70]:
#np 를 통해 만들었기 때문에 그냥 합에서도 아래와 같이 나온다
arr_add_2 = arr_1+arr_2 
print(arr_add_2)

[ 1  4  7 10 13]


In [71]:
#np가 아닌 것의 합은 숫자의 합이 아닌 요소들을 합집합해준다
a_1 = list(range(5))
a_2 = list(range(1,10,2))
a_add_2=a_1+a_2
print(a_add_2)

[0, 1, 2, 3, 4, 1, 3, 5, 7, 9]


In [73]:
arr_subtract_1 = np.subtract(arr_1,arr_2)

print(arr_1)
print(arr_2)
print(arr_subtract_1)

[0 1 2 3 4]
[1 3 5 7 9]
[-1 -2 -3 -4 -5]


In [74]:
#np array 라서 가능한 것임
arr_subtract_2 = arr_1 - arr_2 
print(arr_subtract_2)

[-1 -2 -3 -4 -5]


In [77]:
arr_mul = np.multiply(arr_1,arr_2)

print(arr_1)
print(arr_2)
print(arr_mul)

[0 1 2 3 4]
[1 3 5 7 9]
[ 0  3 10 21 36]


In [78]:
arr_mul_2 = arr_1 * arr_2 
print(arr_mul_2)

[ 0  3 10 21 36]


In [79]:
arr_divide = np.divide(arr_1,arr_2)

print(arr_1)
print(arr_2)
print(arr_divide)

[0 1 2 3 4]
[1 3 5 7 9]
[0.         0.33333333 0.4        0.42857143 0.44444444]


In [80]:
arr_divide_2 = arr_1 / arr_2 
print(arr_divide_2)

[0.         0.33333333 0.4        0.42857143 0.44444444]


In [81]:
arr_mod = np.mod(arr_1,arr_2)

print(arr_1)
print(arr_2)
print(arr_mod)

[0 1 2 3 4]
[1 3 5 7 9]
[0 1 2 3 4]


In [82]:
arr_mod_2 = arr_1 % arr_2 
print(arr_mod_2)

[0 1 2 3 4]


In [83]:
arr_power = np.power(arr_1,arr_2)

print(arr_1)
print(arr_2)
print(arr_power)

[0 1 2 3 4]
[1 3 5 7 9]
[     0      1     32   2187 262144]


In [84]:
arr_power_2 = arr_1 ** arr_2 
print(arr_power_2)

[     0      1     32   2187 262144]


In [88]:
arr_1d_3=np.array([1,2,3])

print(arr_1d_3)
print(arr_1d_3.shape)

[1 2 3]
(3,)


In [89]:
arr_1d_1=np.array([5])
print(arr_1d_1)
print(arr_1d_1.shape)  #요소가 몇개인지 알려주는 것


[5]
(1,)


In [90]:
#요소 개수가 달라도 각각 더할 수 있음 
arr_add = arr_1d_3 + arr_1d_1
print(arr_add)

[6 7 8]


In [94]:
arr_2d_3X3 = np. array([
    [1,4,7],
    [2,5,8],
    [3,6,9]
]
    
)

print(arr_2d_3X3)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [96]:
print(arr_2d_3X3.shape)

(3, 3)


In [98]:
arr_1d_3=np.array([1,0,-1])

print(arr_1d_3)

[ 1  0 -1]


In [99]:
print(arr_1d_3.shape)

(3,)


In [101]:
arr_add = arr_2d_3X3 +arr_1d_3

print(arr_add)

[[2 4 6]
 [3 5 7]
 [4 6 8]]


In [102]:
print(arr_add.shape)

(3, 3)


In [103]:
##88p

In [104]:
#1차원 같지만 2차원임 (주의)
arr_2d_1X3 = np.array([[1,2,3]]) #[]가 두번 들어감

print(arr_2d_1X3)
print(arr_2d_1X3.shape)
print(arr_2d_1X3.ndim)

[[1 2 3]]
(1, 3)
2


In [105]:
arr_2d_3X1 = np.array([
    [1],
    [0],
    [3]])



print(arr_2d_3X1)
print(arr_2d_3X1.shape)
print(arr_2d_3X1.ndim)


[[1]
 [0]
 [3]]
(3, 1)
2


In [106]:
arr_add = arr_2d_1X3+arr_2d_3X1

print(arr_2d_1X3)
print(arr_2d_3X1)
print(arr_add)

print(arr_add.shape)

[[1 2 3]]
[[1]
 [0]
 [3]]
[[2 3 4]
 [1 2 3]
 [4 5 6]]
(3, 3)
