In [ ]:
a = [
    [1,2,3],   #1행 
    [4,5,6]    #2행
    ]

#1,4를 불러오고 싶은데? / 배열끼리의 합 /배열끼리의 계산 등을 하고 싶음 => 넌파이를 통해 가능함

a[1][2]

In [ ]:
# NumPy 설치

! pip install numpy

In [6]:
import numpy

a =  [1,2,3,4,5,6]
print("a: ",a)
print(type(a))

b = numpy.array(a)
print("b :",b)
print(type(b))

a:  [1, 2, 3, 4, 5, 6]
<class 'list'>
b : [1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [8]:
import numpy as np

np.array([1,3,5,7,9])

array([1, 3, 5, 7, 9])

In [9]:
np.array("dataeudu")

array('dataeudu', dtype='<U8')

In [12]:
np.arange(7) #range(7)



array([0, 1, 2, 3, 4, 5, 6])

In [13]:
#파이썬 내장함수

In [16]:
np.ones(5)   # 1차원 배열인데 5개를 1의 요소로 만들겠다

array([1., 1., 1., 1., 1.])

In [15]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [17]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [18]:
np.full(5,4)  #4라는 값을 5번 넣겠다

array([4, 4, 4, 4, 4])

In [19]:
# 값에 .을 찍냐 아니냐의 차이
np.full(5,4).dtype

dtype('int64')

In [21]:
np.full(5,4.).dtype

dtype('float64')

In [22]:
np.full(5,4,dtype="float").dtype

dtype('float64')

In [23]:
# 2차원 배열
#2행 5열
np.array([
    [1,3,5,7,9],
    [2,4,6,8,10]

])

array([[ 1,  3,  5,  7,  9],
       [ 2,  4,  6,  8, 10]])

In [28]:
#3차원 배열
#3행 3열
np. array([[
    [1,2,3]
    [4,5,6]
    [7,8,9]
]])

<>:4: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:4: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\as4761285 001\AppData\Local\Temp\ipykernel_10784\3638477359.py:4: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  [1,2,3]


TypeError: list indices must be integers or slices, not tuple

In [ ]:
np.zeros((2,5,dtype="int"))